version: 2.1
jobs:
  one:
    docker:
      - image: circleci/node:4.8.2
    steps:
      
      - run: echo "hello world"
      - run: sleep 25
  two:
    docker:
      - image: circleci/node:4.8.2
    steps:
     
      - run: echo "A more familiar hi"
      - run: sleep 25
      workflows:
   version: 2
   one_and_two:
     jobs:
       - one
       - two

